Riki auto
Spikes-2212-Programming-Guild/PowerUp-2018 pull request #25
Opened 2018-02-06 12:51 UTC by omri00

2018-02-06 13:19 UTC, TomerSitton requested changes

2018-02-06 13:19 UTC, TomerSitton commented on PowerUp-2018/src/com/spikes2212/robot/Commands/TurnToReflector.java
> +public class TurnToReflector extends DriveArcade {
add a doc line or two plz

2018-02-06 13:19 UTC, TomerSitton commented on PowerUp-2018/src/com/spikes2212/robot/Commands/commandGroups/autonomousCommands/ScoreSwitchFromTheMiddle.java
> +
we dont need the word "the"

2018-02-06 13:19 UTC, TomerSitton commented on PowerUp-2018/src/com/spikes2212/robot/Commands/commandGroups/autonomousCommands/ScoreSwitchFromTheMiddle.java
> +				() -> Robot.gameData.charAt(0) == 'L' ? ROTATION_SPEED.get() : ROTATION_SPEED.get() * -1));
add a comment saying that maybe we want to drive only straight first, then straight and turn, and only then straight and orient

2018-02-06 13:19 UTC, TomerSitton commented on PowerUp-2018/src/com/spikes2212/robot/Robot.java
> +
why isnt this final?

2018-02-06 15:10 UTC, omri00 commented on PowerUp-2018/src/com/spikes2212/robot/Robot.java
> +
because you get it in autoInit

2018-02-06 17:21 UTC, TomerSitton requested changes

2018-02-06 17:21 UTC, TomerSitton commented on PowerUp-2018/src/com/spikes2212/robot/Commands/commandGroups/autonomousCommands/ScoreSwitchFromTheMiddle.java
> +				() -> Robot.gameData.charAt(0) == 'L' ? ROTATION_SPEED.get() : ROTATION_SPEED.get() * -1));
dude..?

2018-02-07 15:16 UTC, TomerSitton approved these changes

2018-02-07 15:17 UTC, merged